feat: refactor introduction widget to be more customizable
Iconica-Development/flutter_introduction_widget pull request #4
Opened 2022-09-21 09:06 UTC by FlutterJoey

A refactor based on the existing refactor available in our nextshell component, hopefully this is not too big of a change at this point

2022-09-21 12:21 UTC, FlutterJorian requested changes

2022-09-21 12:21 UTC, FlutterJorian commented on lib/src/config/introduction.dart
> +  final Widget Function(BuildContext, VoidCallback, Widget)? buttonBuilder;
mist documentatie

2022-09-21 12:21 UTC, FlutterJorian commented on lib/src/introduction.dart
> +
Hier mist nog documentatie voor alle fields

2022-09-21 12:21 UTC, FlutterJorian commented on example/lib/main.dart
> +class MyHomePage extends StatefulWidget {
Hele class kan weg, wordt nergens gebruikt

2022-09-21 12:21 UTC, FlutterJorian commented on example/lib/main.dart
> +import 'package:flutter/cupertino.dart';
Overbodige import, kan weg

2022-09-21 12:21 UTC, FlutterJorian commented on lib/src/config/introduction.dart
> +bool a = true;
wordt niet gebruikt, kan weg

2022-09-21 12:21 UTC, FlutterJorian commented on example/README.md
> +# example
Uitleg over example ipv default flutter app readme

2022-09-21 12:21 UTC, FlutterJorian commented on lib/src/types/single_introduction.dart
> +class SingleIntroductionPage extends StatelessWidget {
Misschien aangeven dat dit nog niet geïmplementeerd is?

2022-09-21 12:21 UTC, FlutterJorian commented on lib/src/types/page_introduction.dart
> +      duration: const Duration(milliseconds: 100),
previousPage = 100 milliseconds, nexPage = 200 en naar page vanaf indicator is 500.
Waarom?

2022-09-22 08:59 UTC, JacquesDIconica approved these changes

2022-09-22 09:04 UTC, merged